sudo: required

language: shell

services:
  - docker

before_install:
  - deploy/build_info.sh | tee build_info.yml
  - echo "travis_branch: $TRAVIS_BRANCH" >> build_info.yml
  - docker build --cache-from jonocodes/pwder:$TRAVIS_BRANCH -t pwder .
  - echo $TRAVIS_BRANCH
  # - docker images

script:
  - docker run pwder bundle exec rspec

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag pwder jonocodes/pwder:$TRAVIS_BRANCH;
    docker push jonocodes/pwder:$TRAVIS_BRANCH;
    fi
